#!/usr/bin/env bash


chown -R ec2-user:www-data "$PWD"

chown -R www-data:www-data "$PWD"/storage
chown -R www-data:www-data "$PWD"/bootstrap

composer install
npm ci
npm run build

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
